name: kevin-lstm
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pandas
  - numpy
  - scikit-learn
  - matplotlib>=3.5.0
  - seaborn>=0.12.0
  - joblib
  - pip
  - pip:
      - yfinance
      - ta
      - tensorflow
      - xgboost
